module.exports.CREEPROLES = {
    harvester: [
        [CARRY, WORK, MOVE],
        [MOVE,MOVE,CARRY,CARRY,WORK,WORK],
        [MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,WORK,WORK,WORK,WORK],
    ],
    upgrader: [
        [CARRY, WORK, MOVE],
        [MOVE,MOVE,CARRY,CARRY,WORK,WORK],
        [MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,WORK,WORK,WORK,WORK],
    ],
    builder: [
        [CARRY, WORK, MOVE],
        [MOVE,MOVE,CARRY,CARRY,WORK,WORK],
        [MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,WORK,WORK,WORK,WORK],
    ],
    repairer: [
        [CARRY, WORK, MOVE],
        [MOVE,MOVE,CARRY,CARRY,WORK,WORK],
        [MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,WORK,WORK,WORK,WORK],
    ],
    defender: [
        [MOVE,ATTACK],
        [MOVE,MOVE,ATTACK,ATTACK],
        [MOVE,MOVE,ATTACK,ATTACK,MOVE,ATTACK],
        [MOVE,MOVE,ATTACK,ATTACK,MOVE,ATTACK,MOVE,MOVE,ATTACK],
        [MOVE,MOVE,ATTACK,ATTACK,MOVE,ATTACK,MOVE,MOVE,ATTACK]
    ],
    attacker: [
        [MOVE,ATTACK],
        [MOVE,MOVE,ATTACK,ATTACK],
        [MOVE,MOVE,ATTACK,ATTACK,MOVE,ATTACK],
        [MOVE,MOVE,ATTACK,ATTACK,MOVE,ATTACK,MOVE,MOVE,ATTACK],
        [MOVE,MOVE,ATTACK,ATTACK,MOVE,ATTACK,MOVE,MOVE,ATTACK]
    ],
    cleaner: [
        [MOVE,MOVE,WORK],
        [MOVE,MOVE,WORK,WORK],
        [MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK],
        [MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK]
    ],
    wallbreaker: [
        [MOVE,MOVE,WORK],
        [MOVE,MOVE,WORK,WORK],
        [MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK],
        [MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK],
    ],
    mover: [
        [CARRY, WORK, MOVE],
        [MOVE,MOVE,CARRY,CARRY,MOVE,MOVE,WORK],
        [MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,WORK],
    ],
    scout: [
        [MOVE,MOVE,MOVE],
        [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
    ],
    rangedbuilder: [
        [CARRY, WORK, MOVE],
        [MOVE,MOVE,CARRY,CARRY,WORK,WORK],
        [MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,WORK,WORK,WORK,WORK],
    ]
}

